FROM nvidia/cuda:11.8.0-base-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app
VOLUME /app/data
VOLUME /app/notebooks

RUN apt-get update && \
    apt-get install -y \
        git \
        python3-pip \
        python3-dev \
        python3-opencv \
        libglib2.0-0

COPY . /app

RUN python3 -m pip install poetry==1.8.3 && \
    poetry config virtualenvs.create false && \
    poetry install --with dev,train

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8889", "--allow-root"]